#!/usr/bin/python
# -*- coding: UTF-8 -*-

"""
Config for app
    Author: lujianyu
    Email:  iam@jianyujianyu.com
"""
from config import LANGUAGE


if LANGUAGE == 'ch':
    text_images_directory = '原图目录'
    text_label = '标签'
    text_label_name = '名称:'
    text_add_label = '创建'
    text_delete_label = '删除'
    text_operating = '操作'
    text_button_images_zoom_1 = '放大 +'
    text_button_images_zoom_2 = '缩小 -'
    text_scaling = '比例: 0%'
    text_scaling_prefix = '比例: '
    text_mode = '模式切换'
    text_view_mode = '观察模式'
    text_create_mode = '标记模式'
    text_delete_mode = '删除模式'
    text_rotate_1 = '生成90°旋转副本'
    text_rotate_2 = '生成180°旋转副本'
    text_zoom = '生成缩放副本'
    text_impurity = '生成杂质副本'
    text_blur = '生成模糊副本'
    text_edge_enhance = '生成边缘增强副本'
    text_noise_reduction = '生成降噪副本'
    text_gray = '生成灰度副本'
    text_generate_one = '【只生成一个副本】'
    text_convert_jpg = '输出转换为JPG'
    text_generate_xml = '生成XML文件以及训练集TXT文件'
    text_remove_useless_labels = '删除无用的标签数据'
    text_copy_option = '副本选项 (配合生成按钮操作)'
    text_generate_option = '生成选项'
    text_add_label_error_title = '创建标签错误'
    text_delete_label_error_title = '删除标签错误'
    text_add_label_error_info = '请输入标签名。'
    text_delete_label_error_info = '请选择标签。'
    text_delete_confirm_title = '删除确认'
    text_delete_confirm_info = '要执行此删除操作吗?'
    text_no_images_title = '无照片'
    text_no_images_info = '指定目录下没有找到照片。'
    text_loading_error_title = '载入错误'
    text_loading_error_info = '请联系开发者。'
    text_has_same_name_error_title = '重名错误'
    text_has_same_name_error_info = '存在不同格式的同名图片，可能会导致程序异常'
    text_remove_useless_labels_title = '删除操作'
    text_remove_useless_labels_info = '如果你点击"ok"，labels文件夹下的无用标签将会被删除！'
    text_processing_function = '处理功能'
    text_rotate_button = '旋转'
    text_edge_enhance_button = '边缘增强'
    text_noise_reduction_button = '降噪'
    text_reset_canvas_image = '还原图片'
    text_save_canvas_image = '保存图片'
else:
    text_images_directory = 'Images directory'
    text_label = 'Labels'
    text_label_name = 'Name:'
    text_add_label = 'Add'
    text_delete_label = 'Delete'
    text_operating = 'Operating'
    text_button_images_zoom_1 = 'Zoom in +'
    text_button_images_zoom_2 = 'Zoom out -'
    text_scaling = 'Rate: 0%'
    text_scaling_prefix = 'Rate: '
    text_mode = 'Modes'
    text_view_mode = 'VIEW MODE'
    text_create_mode = 'CREATE MODE'
    text_delete_mode = 'DELETE MODE'
    text_rotate_1 = '90° Rotate copy'
    text_rotate_2 = '180° Rotate copy'
    text_zoom = 'Zoom copy'
    text_impurity = 'Impurity copy'
    text_blur = 'Blur copy'
    text_edge_enhance = 'Edge enhance copy'
    text_noise_reduction = 'Noise reduction copy'
    text_gray = 'Convert to gray'
    text_generate_one = '[Generate only one copy]'
    text_convert_jpg = 'Convert jpg copy'
    text_generate_xml = 'Generate XML and training TXT'
    text_remove_useless_labels = 'Remove useless labels'
    text_copy_option = 'Copy options (works with generate button)'
    text_generate_option = 'Generate options'
    text_add_label_error_title = 'Add label error'
    text_delete_label_error_title = 'Delete label error'
    text_add_label_error_info = 'Please write label name.'
    text_delete_label_error_info = 'No Selected label.'
    text_delete_confirm_title = 'Delete confirm'
    text_delete_confirm_info = 'Sure to delete?'
    text_no_images_title = 'No image'
    text_no_images_info = 'Image not found under the specified folder.'
    text_loading_error_title = 'Loading error'
    text_loading_error_info = 'Please contact with developers.'
    text_has_same_name_error_title = 'Same name error'
    text_has_same_name_error_info = 'Image with same names but different formats exist, it may make some exceptions'
    text_remove_useless_labels_title = 'Remove operation'
    text_remove_useless_labels_info = 'If you click "ok", useless labels under "labels" will be removed!'
    text_processing_function = 'Image Process'
    text_rotate_button = 'Rotate'
    text_edge_enhance_button = 'Edge enhance'
    text_noise_reduction_button = 'Noise Reduction'
    text_reset_canvas_image = 'Reset Image'
    text_save_canvas_image = 'Save Image'

